-- Simple script to refresh the temp file, if it starts to get very large.
--
-- ref:
-- http://www.idevelopment.info/data/Oracle/DBA_tips/Tablespaces/TBS_3.shtml
--
set echo on

CREATE TEMPORARY TABLESPACE temp2
	TEMPFILE 'C:\OPT\ORACLE\PRODUCT\10.2.0\ORADATA\ORA10\TEMP02.DBF' SIZE 5M REUSE
	AUTOEXTEND ON NEXT 1M MAXSIZE unlimited
	EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;

ALTER DATABASE DEFAULT TEMPORARY TABLESPACE temp2;
DROP TABLESPACE temp INCLUDING CONTENTS AND DATAFILES;

 CREATE TEMPORARY TABLESPACE temp 
	TEMPFILE 'C:\OPT\ORACLE\PRODUCT\10.2.0\ORADATA\ORA10\TEMP01.DBF'
	SIZE 512M REUSE AUTOEXTEND ON NEXT 64M MAXSIZE unlimited
	EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;

ALTER DATABASE DEFAULT TEMPORARY TABLESPACE temp;

DROP TABLESPACE temp2 INCLUDING CONTENTS AND DATAFILES;

set echo off
