TERMINATE FORCE;
DETACH;			
ATTACH TO DB2; 
			
-- QUIESCE DATABASE IMMEDIATE FORCE CONNECTIONS;
BACKUP DATABASE CRTREPO;
BACKUP DATABASE CRTU001;
-- BACKUP DATABASE CRTU002;
BACKUP DATABASE CRTU003;

-- BACKUP DATABASE L3MET;
			
DETACH; 
			
TERMINATE;
		
