REM Tested and fully working as of 9-Feb-10 
REM

REM -- 
REM -- Setup path for the local environment information 
REM --
set DBNAME=BFT
set SCHEMA=%DBNAME%
set DBPATH=C:\DB2\NODE0000\%DBNAME%
set DBALIAS=BUILD
set USER=BUILD

set PAGESIZE=32K

set BPNAME=BUFFP1
set TS_SYSTEMP=TEMPSPACE2
set TS_APPTEMP=BFUSER_TEMP
set TS_APPUSR=USERSPACE2

REM -- Create our database
db2 CREATE DATABASE %DBNAME% ALIAS %DBALIAS% USING CODESET UTF-8 TERRITORY US AUTOCONFIGURE USING MEM_PERCENT 40 APPLY DB ONLY 
REM close any open CLI connections 
db2 TERMINATE 

REM -- Restart our instance. 
db2stop 
db2start 

REM -- Connect to our new database and add the buffer pool. 
db2 CONNECT TO %DBALIAS%
db2 CREATE BUFFERPOOL %BPNAME% IMMEDIATE SIZE 1024 PAGESIZE %PAGESIZE% 

REM -- Close connection and reconnect.
db2 CONNECT RESET 
db2 CONNECT TO %DBALIAS%

REM -- Create system/temp/user tablespaces in current database
db2 CREATE SYSTEM TEMPORARY TABLESPACE %TS_SYSTEMP% PAGESIZE %PAGESIZE% MANAGED BY SYSTEM USING ('%DBPATH%\%TS_SYSTEMP%.0') EXTENTSIZE 64 PREFETCHSIZE 64 BUFFERPOOL %BPNAME% 
db2 CREATE USER TEMPORARY TABLESPACE %TS_APPTEMP% PAGESIZE %PAGESIZE% MANAGED BY SYSTEM USING ('%DBPATH%\%TS_APPTEMP%.0') EXTENTSIZE 64 PREFETCHSIZE 64 BUFFERPOOL %BPNAME% 
db2 CREATE REGULAR TABLESPACE %TS_APPUSR% PAGESIZE %PAGESIZE% MANAGED BY SYSTEM USING ('%DBPATH%\%TS_APPUSR%.0') EXTENTSIZE 64 PREFETCHSIZE 64 BUFFERPOOL %BPNAME% 

REM -- User must be granted use of TSAPPTEMP tablespace 
db2 GRANT USE OF TABLESPACE %TS_APPTEMP% TO USER %USER% WITH GRANT OPTION 
db2 GRANT USE OF TABLESPACE %TS_APPUSR% TO USER %USER% WITH GRANT OPTION 
db2 COMMIT WORK
db2 CONNECT RESET 
db2 TERMINATE

db2 CONNECT TO %DBNAME%
db2 CREATE SCHEMA %SCHEMA%
db2 SET CURRENT SCHEMA = %SCHEMA%
db2 GRANT AlTERIN, CREATEIN, DROPIN ON SCHEMA %SCHEMA% TO %USER%
db2 CONNECT RESET
db2 TERMINATE
