REM Adapted from technote:  http://www-01.ibm.com/support/docview.wss?uid=swg21290313

set DBNAME=BUILD
set DBALIAS=BFT
set DBUSER=db2admin
set FILE_LOC=C:\DB2\NODE0000\SQLDBDIR
set PAGE_SIZE=16384

set BP_NAME=bp_%DBNAME%
set RTS_NAME=rts_%DBNAME%
set UTTS_NAME=utts_%DBNAME%
set STTS_NAME=stts_%DBNAME%

REM  Create database
db2 CREATE DATABASE %DBNAME% ALIAS %DBALIAS% AUTOCONFIGURE USING MEM_PERCENT 40 APPLY DB ONLY USING CODESET UTF-8 TERRITORY US
db2 CONNECT TO %DBNAME%

db2 CREATE BUFFERPOOL %BP_NAME% IMMEDIATE SIZE 1000 PAGESIZE %PAGE_SIZE%
db2 CONNECT RESET
db2 CONNECT TO %DBNAME%

REM Create tablespaces
db2 CREATE SYSTEM TEMPORARY TABLESPACE %STTS_NAME% PAGESIZE %PAGE_SIZE% MANAGED BY SYSTEM  USING ('%FILE_LOC%/%STTS_NAME%.0')  EXTENTSIZE 64 PREFETCHSIZE 64  BUFFERPOOL %BP_NAME%

db2 CREATE USER TEMPORARY TABLESPACE %UTTS_NAME% PAGESIZE %PAGE_SIZE% MANAGED BY SYSTEM  USING ('%FILE_LOC%/%UTTS_NAME%.0') EXTENTSIZE 64  PREFETCHSIZE 64  BUFFERPOOL %BP_NAME%

db2 CREATE REGULAR TABLESPACE %RTS_NAME% PAGESIZE %PAGE_SIZE% MANAGED BY SYSTEM  USING ('%FILE_LOC%/%RTS_NAME%.0')  EXTENTSIZE 64  PREFETCHSIZE 64  BUFFERPOOL %BP_NAME%

REM User must be granted use of BFUSE_TEMP tablespace
db2 GRANT USE OF TABLESPACE %UTTS_NAME% TO USER %DBUSER% WITH GRANT OPTION

db2 COMMIT WORK

db2 CREATE SCHEMA %DBNAME%
db2 SET CURRENT SCHEMA = %DBNAME%

db2 CONNECT RESET
db2 TERMINATE